module.exports = [
{
  quote: 'Tell me and I forget. Teach me and I remember. Involve me and I learn.',
  who: '-Benjamin Franklin',
  when: '',
  where: '',
  factChecked: true,
},
{
  quote: "Don't judge each day by the harvest you reap but by the seeds that you plant.",
  who: '-Robert Louis Stevenson',
  when: '',
  where: '',
  factChecked: true,
},
{
  quote: 'The future belongs to those who believe in the beauty of their dreams.',
  who: '-Eleanor Roosevelt',
  when: '',
  where: '',
  factChecked: true,
},
{
  quote: 'The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.',
  who: '-Helen Keller',
  when: '',
  where: '',
  factChecked: true,
},
{
  quote: 'Whoever is happy will make others happy too.',
  who: '-Anne Frank',
  when: '',
  where: '',
  factChecked: true,
},
{
  quote: 'Do not go where the path may lead, go instead where there is no path and leave a trail.',
  who: '-Ralph Waldo Emerson',
  when: '',
  where: '',
  factChecked: true,
},
{
  quote: 'Always remember that you are absolutely unique. Just like everyone else.',
  who: '-Margaret Mead',
  when: '',
  where: '',
  factChecked: true,
},
{
  quote: 'You will face many defeats in life, but never let yourself be defeated.',
  who: '-Maya Angelou',
  when: '',
  where: '',
  factChecked: true,
},
{
  quote: "In the end, it's not the years in your life that count. It's the life in your years.",
  who: '-Abraham Lincoln',
  when: '',
  where: '',
  factChecked: true,
},
{
  quote: "The best revenge is massive success.",
  who: '-Frank Sinatra',
  when: '',
  where: '',
  factChecked: true,
},

]
